### ISSUE TITLE
Social login popup 

### ISSUE THREAD

**Issue by NikTopler** [NikTopler/FootballNews#2]
CSS animations not working fluently.

```HTML
<div class="button-container">
      <button (click)="google()" class="google social-button">
         <!-- code -->
    </button>
</div>
```

```SCSS
.button-container {
  padding-top: 3px;
  padding-bottom: 0;
  transition: all ease-in .18s;
}

.button-container:hover {
  padding-top: 0;
  padding-bottom: 3px;
}
```
